use bitflags::bitflags;
use windows::Win32::Graphics::Direct3D::Fxc::{
	D3DCOMPILE_DEBUG,
	D3DCOMPILE_SKIP_VALIDATION,
	D3DCOMPILE_SKIP_OPTIMIZATION,
	D3DCOMPILE_PACK_MATRIX_ROW_MAJOR,
	D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR,
	D3DCOMPILE_PARTIAL_PRECISION,
	D3DCOMPILE_FORCE_VS_SOFTWARE_NO_OPT,
	D3DCOMPILE_FORCE_PS_SOFTWARE_NO_OPT,
	D3DCOMPILE_NO_PRESHADER,
	D3DCOMPILE_AVOID_FLOW_CONTROL,
	D3DCOMPILE_ENABLE_STRICTNESS,
	D3DCOMPILE_IEEE_STRICTNESS,
	D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY,
	D3DCOMPILE_OPTIMIZATION_LEVEL0,
	D3DCOMPILE_OPTIMIZATION_LEVEL1,
	D3DCOMPILE_OPTIMIZATION_LEVEL3,
	D3DCOMPILE_WARNINGS_ARE_ERRORS,
	D3DCOMPILE_RESOURCES_MAY_ALIAS,
	D3DCOMPILE_ENABLE_UNBOUNDED_DESCRIPTOR_TABLES,
	D3DCOMPILE_ALL_RESOURCES_BOUND,
	D3DCOMPILE_DEBUG_NAME_FOR_SOURCE,
	D3DCOMPILE_DEBUG_NAME_FOR_BINARY
};
use windows::Win32::Graphics::Hlsl::D3DCOMPILE_OPTIMIZATION_LEVEL2;



bitflags! {
	pub struct CompileFlags: u32 {
		const DEBUG = D3DCOMPILE_DEBUG;
		const SKIP_VALIDATION = D3DCOMPILE_SKIP_VALIDATION;
		const SKIP_OPTIMIZATION = D3DCOMPILE_SKIP_OPTIMIZATION;
		const PACK_MATRIX_ROW_MAJOR = D3DCOMPILE_PACK_MATRIX_ROW_MAJOR;
		const PACK_MATRIX_COLUMN_MAJOR = D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR;
		const PARTIAL_PRECISION = D3DCOMPILE_PARTIAL_PRECISION;
		const FORCE_VS_SOFTWARE_NO_OPT = D3DCOMPILE_FORCE_VS_SOFTWARE_NO_OPT;
		const FORCE_PS_SOFTWARE_NO_OPT = D3DCOMPILE_FORCE_PS_SOFTWARE_NO_OPT;
		const NO_PRESHADER = D3DCOMPILE_NO_PRESHADER;
		const AVOID_FLOW_CONTROL = D3DCOMPILE_AVOID_FLOW_CONTROL;
		const ENABLE_STRICTNESS = D3DCOMPILE_ENABLE_STRICTNESS;
		const IEEE_STRICTNESS = D3DCOMPILE_IEEE_STRICTNESS;
		const ENABLE_BACKWARDS_COMPATIBILITY = D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY;
		const OPTIMIZATION_LEVEL0 = D3DCOMPILE_OPTIMIZATION_LEVEL0;
		const OPTIMIZATION_LEVEL1 = D3DCOMPILE_OPTIMIZATION_LEVEL1;
		const OPTIMIZATION_LEVEL2 = D3DCOMPILE_OPTIMIZATION_LEVEL2;
		const OPTIMIZATION_LEVEL3 = D3DCOMPILE_OPTIMIZATION_LEVEL3;
		const WARNINGS_ARE_ERRORS = D3DCOMPILE_WARNINGS_ARE_ERRORS;
		const RESOURCES_MAY_ALIAS = D3DCOMPILE_RESOURCES_MAY_ALIAS;
		const ENABLE_UNBOUNDED_DESCRIPTOR_TABLES = D3DCOMPILE_ENABLE_UNBOUNDED_DESCRIPTOR_TABLES;
		const ALL_RESOURCES_BOUND = D3DCOMPILE_ALL_RESOURCES_BOUND;
		const DEBUG_NAME_FOR_SOURCE = D3DCOMPILE_DEBUG_NAME_FOR_SOURCE;
		const DEBUG_NAME_FOR_BINARY = D3DCOMPILE_DEBUG_NAME_FOR_BINARY;
	}
}